spring:
  application.name: Platform Gateway
  main.banner-mode: off

server:
  port: 8080

management:
  endpoint.prometheus.enabled: true
  endpoints:
    web.base-path: /gateway
    enabled-by-default: false
    web.exposure.include: prometheus
    web.path-mapping.prometheus: prometheus-metrics
